import { RepositoryClient } from "../repository/repository-client.js";
import { buildAuthorQuery, buildArxivApiUrl, fetchArxivPapers, isAuthorCacheFresh } from "../services/arxiv-paper-service.js";
import { paperRow, setBookmarkState } from "../ui/paper-row.js";
const repository=new RepositoryClient();const element=id=>document.getElementById(id);const authorId=new URL(location.href).searchParams.get("authorId");let author;let savedIds=new Set();let query;
element("refresh").addEventListener("click",()=>void refresh(true));element("open-search").addEventListener("click",()=>chrome.tabs.create({url:`https://arxiv.org/search/?query=${encodeURIComponent(author?.displayName||"")}&searchtype=author`}));void init();
async function init(){try{const library=await repository.getAuthorLibrary();author=library.authors.find(item=>item.id===authorId);if(!author)throw new Error("This researcher is not in the local author library.");query=buildAuthorQuery(author);element("name").textContent=author.displayName;document.title=`${author.displayName} — Researcher Papers`;
 const memberships=library.memberships.filter(m=>m.authorId===author.id);element("follow-state").textContent=memberships.length?"Following":"Not currently followed";const ids=new Set(memberships.map(m=>m.collectionId));element("collections").textContent=`Collections: ${library.collections.filter(c=>ids.has(c.id)).map(c=>c.name).join(" · ")||"None"}`;
 savedIds=new Set((await repository.listFavorites()).map(p=>p.arxivId));const cache=await repository.getAuthorPaperCache(author.id);if(cache){render(cache.papers,cache.fetchedAt);if(!isAuthorCacheFresh(cache))void refresh(false)}else await refresh(false);
 }catch(error){setStatus(error.message,true);element("refresh").disabled=true;element("open-search").disabled=true}}
async function refresh(manual){element("refresh").disabled=true;setStatus(manual?"Refreshing from arXiv…":"Loading papers from arXiv…");try{const papers=await fetchArxivPapers(query);const cache=await repository.putAuthorPaperCache({authorId:author.id,papers,fetchedAt:new Date().toISOString(),queryUsed:query});savedIds=new Set((await repository.listFavorites()).map(p=>p.arxivId));render(cache.papers,cache.fetchedAt);setStatus("")}catch(error){setStatus(`Could not refresh: ${error.message}`,true)}finally{element("refresh").disabled=false}}
function render(papers,fetchedAt){element("updated").textContent=`Updated ${new Date(fetchedAt).toLocaleString()}`;const groups=new Map();for(const paper of papers){const year=new Date(paper.publishedAt).getFullYear();if(!groups.has(year))groups.set(year,[]);groups.get(year).push(paper)}
 const fragment=document.createDocumentFragment();for(const [year,items] of groups){const heading=document.createElement("h2");heading.className="year";heading.textContent=year;const list=document.createElement("ul");list.className="year-list";list.append(...items.map(p=>paperRow(p,{saved:savedIds.has(p.arxivId),onToggle:b=>toggle(p,b)})));fragment.append(heading,list)}element("papers").replaceChildren(fragment);element("empty").hidden=papers.length>0;}
async function toggle(paper,button){button.disabled=true;try{const result=await repository.toggleFavorite(paper);if(result)savedIds.add(paper.arxivId);else savedIds.delete(paper.arxivId);setBookmarkState(button,Boolean(result),paper.title);setStatus(result?"Paper saved.":"Paper removed from the library.")}catch(error){setStatus(error.message,true)}finally{button.disabled=false}}
function setStatus(message,error=false){element("status").textContent=message;element("status").classList.toggle("error",error)}
