import { RepositoryClient } from "../repository/repository-client.js";
import { buildAuthorQuery, buildArxivApiUrl, fetchArxivPapers, isAuthorCacheFresh, paperMatchesAuthor } from "../services/arxiv-paper-service.js";
import { paperRow, setBookmarkState } from "../ui/paper-row.js";
import { openPaperCollectionPicker } from "../ui/paper-collection-picker.js";
const repository=new RepositoryClient();const element=id=>document.getElementById(id);const authorId=new URL(location.href).searchParams.get("authorId");let author;let savedIds=new Set();let query;
element("refresh").addEventListener("click",()=>void refresh(true));element("open-search").addEventListener("click",()=>chrome.tabs.create({url:`https://arxiv.org/search/?query=${encodeURIComponent(author?.displayName||"")}&searchtype=author`}));void init();
async function init(){try{const library=await repository.getAuthorLibrary();author=library.authors.find(item=>item.id===authorId);if(!author)throw new Error("This researcher is not in the local author library.");query=buildAuthorQuery(author);element("name").textContent=author.displayName;document.title=`${author.displayName} — Researcher Papers`;
 savedIds=new Set((await repository.listFavorites()).map(p=>p.arxivId));const cache=await repository.getAuthorPaperCache(author.id);if(cache){render(cache.papers,cache.fetchedAt);if(!isAuthorCacheFresh(cache))void refresh(false)}else await refresh(false);
 }catch(error){setStatus(error.message,true);element("refresh").disabled=true;element("open-search").disabled=true}}
async function refresh(manual){element("refresh").disabled=true;setStatus(manual?"Refreshing from arXiv…":"Loading papers from arXiv…");try{const papers=await fetchArxivPapers(query);const cache=await repository.putAuthorPaperCache({authorId:author.id,papers,fetchedAt:new Date().toISOString(),queryUsed:query});savedIds=new Set((await repository.listFavorites()).map(p=>p.arxivId));render(cache.papers,cache.fetchedAt);setStatus("")}catch(error){setStatus(`Could not refresh: ${error.message}`,true)}finally{element("refresh").disabled=false}}
function render(papers,fetchedAt){papers=papers.filter(paper=>paperMatchesAuthor(paper,author));element("updated").textContent=`Updated ${new Date(fetchedAt).toLocaleString()}`;const groups=new Map();for(const paper of papers){const year=new Date(paper.publishedAt).getFullYear();if(!groups.has(year))groups.set(year,[]);groups.get(year).push(paper)}
 const fragment=document.createDocumentFragment();for(const [year,items] of groups){const section=document.createElement("section");section.className="year-group";const heading=document.createElement("h2");heading.className="year";heading.id=`year-${year}`;heading.textContent=year;section.setAttribute("aria-labelledby",heading.id);const list=document.createElement("ul");list.className="year-list";list.append(...items.map(p=>paperRow(p,{saved:savedIds.has(p.arxivId),onToggle:b=>save(p,b)})));section.append(heading,list);fragment.append(section)}element("papers").replaceChildren(fragment);element("empty").hidden=papers.length>0;}
async function save(paper,button){if(savedIds.has(paper.arxivId)){button.setAttribute("aria-haspopup","dialog");button.setAttribute("aria-expanded","false");await openPaperCollectionPicker({repository,paper,anchor:button,onChange:()=>syncBookmark(paper,button)});return}button.disabled=true;try{await repository.savePaper(paper);savedIds.add(paper.arxivId);setBookmarkState(button,true,paper.title);setStatus("Paper saved.")}catch(error){setStatus(error.message,true)}finally{button.disabled=false}}
async function syncBookmark(paper,button){savedIds=new Set((await repository.listFavorites()).map(item=>item.arxivId));setBookmarkState(button,savedIds.has(paper.arxivId),paper.title);setStatus(savedIds.has(paper.arxivId)?"Paper collections updated.":"Paper removed from the library.")}
function setStatus(message,error=false){element("status").textContent=message;element("status").classList.toggle("error",error)}
