import { RepositoryClient } from "../repository/repository-client.js";
import { FIELD_PRESETS } from "./field-presets.js";import { expandQuery } from "./expand-query.js";import { buildArxivSearchUrl } from "./arxiv-search-url.js";
import { buildApiQuery, fetchArxivPapers } from "../services/arxiv-paper-service.js";import { paperRow, setBookmarkState } from "../ui/paper-row.js";
const repository=new RepositoryClient();const element=id=>document.getElementById(id);let currentPlan;let savedIds=new Set();for(const field of FIELD_PRESETS)element("field").append(new Option(field.name,field.id));
element("search-form").addEventListener("input",preview);element("search-form").addEventListener("submit",event=>{event.preventDefault();void search()});element("native-search").addEventListener("click",()=>{try{const plan=planFromForm();chrome.tabs.create({url:buildArxivSearchUrl(plan)})}catch(error){setStatus(error.message,true)}});void loadSaved();
function planFromForm(){return expandQuery({query:element("query").value,fieldId:element("field").value,mode:document.querySelector('input[name="mode"]:checked').value})}function preview(){try{currentPlan=planFromForm();element("preview").textContent=currentPlan.expandedQuery;setStatus("")}catch(error){element("preview").textContent=error.message}}
async function loadSaved(){savedIds=new Set((await repository.listFavorites()).map(p=>p.arxivId))}
async function search(){try{currentPlan=planFromForm();element("preview").textContent=currentPlan.expandedQuery;setStatus("Searching arXiv…");await loadSaved();const papers=await fetchArxivPapers(buildApiQuery(currentPlan));element("results").replaceChildren(...papers.map(p=>paperRow(p,{saved:savedIds.has(p.arxivId),onToggle:b=>toggle(p,b)})));element("empty").hidden=papers.length>0;setStatus("")}catch(error){setStatus(`Direct results unavailable: ${error.message} Use “Open on arXiv” to view the same search.`,true)}}
async function toggle(paper,button){button.disabled=true;try{const result=await repository.toggleFavorite(paper);if(result)savedIds.add(paper.arxivId);else savedIds.delete(paper.arxivId);setBookmarkState(button,Boolean(result),paper.title);setStatus(result?"Paper saved.":"Paper removed from the library.")}catch(error){setStatus(error.message,true)}finally{button.disabled=false}}
function setStatus(message,error=false){element("status").textContent=message;element("status").classList.toggle("error",error)}
