import { RepositoryClient } from "../repository/repository-client.js";
import { FIELD_PRESETS } from "./field-presets.js";import { expandQuery } from "./expand-query.js";import { buildArxivSearchUrl } from "./arxiv-search-url.js";
import { buildApiQuery, fetchArxivPapers } from "../services/arxiv-paper-service.js";import { paperRow, setBookmarkState } from "../ui/paper-row.js";
import { openPaperCollectionPicker } from "../ui/paper-collection-picker.js";
import { configureArxivLink } from "../ui/arxiv-link.js";
const repository=new RepositoryClient();const element=id=>document.getElementById(id);let currentPlan;let savedIds=new Set();let openArxivLinksInNewTab=false;for(const field of FIELD_PRESETS)element("field").append(new Option(field.name,field.id));
element("search-form").addEventListener("input",preview);element("search-form").addEventListener("submit",event=>{event.preventDefault();void search()});void loadSaved();
function planFromForm(){return expandQuery({query:element("query").value,fieldId:element("field").value,mode:document.querySelector('input[name="mode"]:checked').value})}function preview(){try{currentPlan=planFromForm();element("preview").textContent=currentPlan.expandedQuery;element("native-search").href=buildArxivSearchUrl(currentPlan);setStatus("")}catch(error){element("preview").textContent=error.message}}
async function loadSaved(){const [papers,preferences]=await Promise.all([repository.listFavorites(),repository.getPreferences()]);savedIds=new Set(papers.map(p=>p.arxivId));openArxivLinksInNewTab=preferences.openArxivLinksInNewTab;configureArxivLink(element("native-search"),openArxivLinksInNewTab)}
async function search(){try{currentPlan=planFromForm();element("preview").textContent=currentPlan.expandedQuery;element("native-search").href=buildArxivSearchUrl(currentPlan);setStatus("Searching arXiv…");await loadSaved();const papers=await fetchArxivPapers(buildApiQuery(currentPlan));element("results").replaceChildren(...papers.map(p=>paperRow(p,{saved:savedIds.has(p.arxivId),onToggle:b=>toggle(p,b),openArxivLinksInNewTab})));element("empty").hidden=papers.length>0;setStatus("")}catch(error){setStatus(`Direct results unavailable: ${error.message} Use “Open on arXiv” to view the same search.`,true)}}
async function toggle(paper,button){if(savedIds.has(paper.arxivId)){button.setAttribute("aria-haspopup","dialog");button.setAttribute("aria-expanded","false");await openPaperCollectionPicker({repository,paper,anchor:button,onChange:()=>syncBookmark(paper,button)});return}button.disabled=true;try{await repository.savePaper(paper);savedIds.add(paper.arxivId);setBookmarkState(button,true,paper.title);setStatus("Paper saved.")}catch(error){setStatus(error.message,true)}finally{button.disabled=false}}
async function syncBookmark(paper,button){await loadSaved();setBookmarkState(button,savedIds.has(paper.arxivId),paper.title);setStatus(savedIds.has(paper.arxivId)?"Paper collections updated.":"Paper removed from the library.")}
function setStatus(message,error=false){element("status").textContent=message;element("status").classList.toggle("error",error)}
