import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root=fileURLToPath(new URL("../",import.meta.url));const profile=await mkdtemp(join(tmpdir(),"arxiv-smoke-"));
const chrome=spawn(process.env.CHROME_BIN||"/usr/bin/google-chrome",["--headless=new","--no-sandbox","--disable-gpu","--disable-dev-shm-usage","--no-first-run","--disable-background-networking","--remote-debugging-pipe","--enable-unsafe-extension-debugging",`--user-data-dir=${profile}`,"about:blank"],{stdio:["ignore","ignore","pipe","pipe","pipe"]});
let nextId=0,buffer="",errors="";const pending=new Map(),listeners=[],runtimeErrors=[],asyncErrors=[];chrome.stderr.on("data",d=>errors+=d);
for(const stream of [chrome.stdio[3],chrome.stdio[4]])stream.on("error",e=>asyncErrors.push(e.message));
chrome.stdio[4].on("data",data=>{buffer+=data;let index;while((index=buffer.indexOf("\0"))>=0){const message=JSON.parse(buffer.slice(0,index));buffer=buffer.slice(index+1);if(message.id){const callback=pending.get(message.id);pending.delete(message.id);message.error?callback?.reject(new Error(JSON.stringify(message.error))):callback?.resolve(message.result)}else listeners.forEach(listener=>listener(message))}});
function send(method,params={},sessionId){return new Promise((resolve,reject)=>{const id=++nextId;const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`Timeout: ${method}\n${errors.slice(-2000)}`))},15000);pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value)},reject:error=>{clearTimeout(timer);reject(error)}});chrome.stdio[3].write(JSON.stringify({id,method,params,sessionId})+"\0")})}
async function evaluate(sessionId,expression){const result=await send("Runtime.evaluate",{expression,returnByValue:true,awaitPromise:true},sessionId);if(result.exceptionDetails)throw new Error(JSON.stringify(result.exceptionDetails));return result.result.value}
async function until(sessionId,expression){for(let i=0;i<80;i++){if(await evaluate(sessionId,expression))return;await new Promise(resolve=>setTimeout(resolve,100))}throw new Error(`Condition not met: ${expression}\n${await evaluate(sessionId,"document.body.innerText")}`)}
async function page(){const {targetId}=await send("Target.createTarget",{url:"about:blank"});const {sessionId}=await send("Target.attachToTarget",{targetId,flatten:true});await send("Page.enable",{},sessionId);await send("Runtime.enable",{},sessionId);return{targetId,sessionId}}
async function nativeClick(sessionId,selector,modifiers=0,button="left"){const point=await evaluate(sessionId,`(()=>{const rect=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:rect.left+rect.width/2,y:rect.top+rect.height/2}})()`);await send("Input.dispatchMouseEvent",{type:"mousePressed",x:point.x,y:point.y,button,buttons:button==="middle"?4:1,clickCount:1,modifiers},sessionId);await send("Input.dispatchMouseEvent",{type:"mouseReleased",x:point.x,y:point.y,button,buttons:0,clickCount:1,modifiers},sessionId)}
async function createdTarget(operation,predicate=()=>true){const before=new Set((await send("Target.getTargets")).targetInfos.map(target=>target.targetId));await operation();for(let i=0;i<40;i++){const targets=await send("Target.getTargets");const target=targets.targetInfos.find(item=>item.type==="page"&&!before.has(item.targetId)&&predicate(item));if(target)return target;await new Promise(resolve=>setTimeout(resolve,100))}throw new Error("Expected click to create a browser target")}
const fixture=(await readFile(join(root,"tests/fixtures/arxiv-abstract.html"),"utf8")).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"");
const atom=`<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom"><entry><id>https://arxiv.org/abs/2609.01234v1</id><title>Recent mirror symmetry paper</title><summary>A normalized result for browser verification.</summary><published>2026-09-20T00:00:00Z</published><author><name>Alex Kim</name></author><category term="math.AG"/></entry></feed>`;
const intercepted=new Map();listeners.push(message=>{if(message.method==="Runtime.exceptionThrown")runtimeErrors.push(message.params);if(message.method==="Runtime.consoleAPICalled"&&message.params.type==="error")runtimeErrors.push(message.params.args);if(message.method==="Fetch.requestPaused"&&intercepted.has(message.sessionId)){const url=message.params.request.url;const body=url.startsWith("https://export.arxiv.org/")?atom:fixture;void send("Fetch.fulfillRequest",{requestId:message.params.requestId,responseCode:200,responseHeaders:[{name:"Content-Type",value:url.includes("export.arxiv.org")?"application/atom+xml":"text/html; charset=utf-8"}],body:Buffer.from(message.params.resourceType==="Document"||url.includes("export.arxiv.org")?body:"").toString("base64")},message.sessionId).catch(e=>asyncErrors.push(e.message))}});
async function intercept(sessionId){intercepted.set(sessionId,true);await send("Fetch.enable",{patterns:[{urlPattern:"https://*"}]},sessionId)}

try{
  const loaded=await send("Extensions.loadUnpacked",{path:join(root,"extension")});const extensionId=loaded.id;const extensionUrl=path=>`chrome-extension://${extensionId}/src/${path}`;
  const {sessionId:arxiv}=await page();await intercept(arxiv);await send("Page.navigate",{url:"https://arxiv.org/abs/2401.00001"},arxiv);
  await until(arxiv,"document.querySelector('.arxiv-library-bookmark') && document.querySelectorAll('.authors .arxiv-library-button').length===2 && !document.querySelector('.arxiv-library-bookmark').disabled");
  assert.equal(await evaluate(arxiv,"document.querySelector('.arxiv-library-bookmark').getBoundingClientRect().width>=36 && document.querySelector('.arxiv-library-bookmark svg').getBoundingClientRect().width>=20"),true);
  assert.equal(await evaluate(arxiv,"(()=>{const button=document.querySelector('.authors .arxiv-library-button');const rect=button.getBoundingClientRect();return button.textContent==='Follow'&&button.getAttribute('aria-pressed')==='false'&&!button.hasAttribute('aria-haspopup')&&rect.height>=36&&rect.width>=78})()"),true);
  await evaluate(arxiv,"document.querySelector('.arxiv-library-bookmark').click()");await until(arxiv,"document.querySelector('.arxiv-library-bookmark').getAttribute('aria-pressed')==='true' && !document.querySelector('.arxiv-library-bookmark').disabled");
  await evaluate(arxiv,"document.querySelector('.authors .arxiv-library-button').click()");await until(arxiv,"document.querySelector('.authors .arxiv-library-button').getAttribute('aria-pressed')==='true'");
  assert.equal(await evaluate(arxiv,"document.querySelector('.authors .arxiv-library-button').textContent"),"Following");
  assert.equal(await evaluate(arxiv,"(()=>{const button=document.querySelector('.authors .arxiv-library-button'),style=getComputedStyle(button);return Boolean(button.querySelector('svg'))&&style.backgroundColor!=='rgb(25, 26, 27)'&&style.boxShadow.includes('inset')})()"),true);
  await evaluate(arxiv,"document.querySelector('.authors .arxiv-library-button').click()");await until(arxiv,"document.querySelector('.authors .arxiv-library-button').getAttribute('aria-pressed')==='false'");
  await evaluate(arxiv,"document.querySelector('.authors .arxiv-library-button').click()");await until(arxiv,"document.querySelector('.authors .arxiv-library-button').getAttribute('aria-pressed')==='true'");
  assert.equal(await evaluate(arxiv,"document.querySelector('.arxiv-library-bookmark').title"),"Manage collections");
  await evaluate(arxiv,"document.querySelector('.arxiv-library-bookmark').click()");await until(arxiv,"document.querySelector('.arxiv-collection-picker') && document.querySelectorAll('.arxiv-collection-picker input[type=checkbox]:checked').length===1");
  assert.equal(await evaluate(arxiv,"[...document.querySelectorAll('.arxiv-collection-picker label')].find(l=>l.textContent.includes('Saved Papers'))?.querySelector('input').checked"),true);
  await evaluate(arxiv,"document.querySelector('.arxiv-collection-picker input[type=text]').value='Important';document.querySelector('.arxiv-collection-picker form').requestSubmit()");
  await until(arxiv,"document.querySelectorAll('.arxiv-collection-picker input[type=checkbox]:checked').length===2");

  const {targetId:popupPageTarget,sessionId:popup}=await page();await send("Page.navigate",{url:extensionUrl("popup/popup.html")},popup);await until(popup,"document.querySelector('#saved-count')?.textContent==='1' && document.querySelector('#following-count')?.textContent==='1' && !document.querySelector('#open-arxiv-new-tab').checked");
  assert.deepEqual(await evaluate(popup,"chrome.action.openPopup().then(()=>({ok:true}),error=>({ok:false,error:error.message}))"),{ok:true});
  let actionPopup;for(let i=0;i<30&&!actionPopup;i++){const targets=await send("Target.getTargets");actionPopup=targets.targetInfos.find(target=>target.type==="page"&&target.url===extensionUrl("popup/popup.html")&&target.targetId!==popupPageTarget);if(!actionPopup)await new Promise(resolve=>setTimeout(resolve,50))}assert.ok(actionPopup,"Chrome action popup did not open");
  const {sessionId:actionPopupSession}=await send("Target.attachToTarget",{targetId:actionPopup.targetId,flatten:true});await send("Page.enable",{},actionPopupSession);await send("Runtime.enable",{},actionPopupSession);await until(actionPopupSession,"document.readyState==='complete' && document.querySelector('#saved-count')?.textContent==='1' && document.querySelector('#following-count')?.textContent==='1'");await evaluate(actionPopupSession,"document.fonts.ready.then(()=>true)");
  const geometryExpression="(()=>{const html=document.documentElement,body=document.body,buttons=[...document.querySelectorAll('nav button')].map(button=>{const rect=button.getBoundingClientRect();return [rect.x,rect.y,rect.width,rect.height]});return{viewport:[innerWidth,innerHeight],body:[body.getBoundingClientRect().width,body.getBoundingClientRect().height],overflow:[html.clientWidth,html.scrollWidth,body.clientWidth,body.scrollWidth],buttons}})()";
  const popupGeometry=await evaluate(actionPopupSession,geometryExpression);assert.equal(popupGeometry.viewport[0],408);assert.equal(popupGeometry.overflow[0],popupGeometry.overflow[1]);assert.equal(popupGeometry.overflow[2],popupGeometry.overflow[3]);assert.deepEqual(popupGeometry.buttons[0].slice(2),popupGeometry.buttons[1].slice(2));
  for(let i=0;i<10;i++){await new Promise(resolve=>setTimeout(resolve,50));assert.deepEqual(await evaluate(actionPopupSession,geometryExpression),popupGeometry)}
  await evaluate(actionPopupSession,"document.querySelector('nav button').focus()");assert.deepEqual(await evaluate(actionPopupSession,geometryExpression),popupGeometry);
  const buttonCenter=await evaluate(actionPopupSession,"(()=>{const rect=document.querySelector('nav button').getBoundingClientRect();return{x:rect.left+rect.width/2,y:rect.top+rect.height/2}})()");await send("Input.dispatchMouseEvent",{type:"mouseMoved",x:buttonCenter.x,y:buttonCenter.y},actionPopupSession);assert.deepEqual(await evaluate(actionPopupSession,geometryExpression),popupGeometry);
  assert.deepEqual(await evaluate(popup,"[...document.querySelectorAll('nav button')].map(button=>button.querySelector('span').textContent)"),["Library","Following"]);
  assert.equal(await evaluate(popup,"!document.querySelector('dl')&&document.querySelectorAll('nav button').length===2"),true);
  assert.equal(await evaluate(popup,"document.fonts.check('15px \\\"IBM Plex Sans\\\"')&&getComputedStyle(document.documentElement).fontFamily.startsWith('\\\"IBM Plex Sans\\\"')"),true);
  assert.equal(await evaluate(popup,"(()=>{const body=document.body.getBoundingClientRect(),main=getComputedStyle(document.querySelector('main')),buttons=[...document.querySelectorAll('nav button')].map(button=>button.getBoundingClientRect()),nav=document.querySelector('nav').getBoundingClientRect();return body.width===408&&main.paddingLeft===main.paddingRight&&buttons[0].width===buttons[1].width&&buttons[0].height===44&&buttons[1].height===44&&Math.abs((buttons[1].top-buttons[0].bottom)-2)<.1&&Math.abs(nav.left-body.left-16)<.1&&Math.abs(body.right-nav.right-16)<.1})()"),true);
  const popupBeforeCountChange=await evaluate(popup,geometryExpression);await evaluate(popup,"document.querySelector('#saved-count').textContent='8888';document.querySelector('#following-count').textContent='9999'");assert.deepEqual(await evaluate(popup,geometryExpression),popupBeforeCountChange);
  await evaluate(popup,"window.close=()=>{}");
  for(const [label,path] of [["Library","library/library.html"],["Following","authors/authors.html"]]){await evaluate(popup,`document.querySelector('[data-page=${JSON.stringify(path)}]').click()`);for(let i=0;i<30;i++){const targets=await send("Target.getTargets");if(targets.targetInfos.some(t=>t.url===extensionUrl(path)))break;if(i===29)assert.fail(`${label} did not open ${path}`);await new Promise(r=>setTimeout(r,100))}}

  const {sessionId:library}=await page();await send("Page.navigate",{url:extensionUrl("library/library.html")},library);await until(library,"document.querySelectorAll('#papers .paper-row').length===1");assert.equal(await evaluate(library,"document.querySelector('#papers h2').textContent"),"A sample paper");
  assert.equal(await evaluate(library,"[...document.querySelectorAll('.app-nav a')].some(link=>link.textContent==='Search')"),false);
  assert.deepEqual(await evaluate(library,"[...document.querySelectorAll('.app-nav a')].map(link=>link.textContent)"),["Library","Following"]);
  assert.deepEqual(await evaluate(library,"[...document.querySelectorAll('#collection-list .collection-link')].map(button=>[button.firstElementChild.textContent,button.lastElementChild.textContent,button.getAttribute('aria-current')])"),[["All Saved","1","page"],["Saved Papers","1",null],["Important","1",null]]);
  assert.equal(await evaluate(library,"Boolean(document.querySelector('aside nav')) && !document.querySelector('select')"),true);
  assert.equal(await evaluate(library,"!document.querySelector('#show-manage')&&!document.querySelector('#manage-form')"),true);
  await send("Emulation.setDeviceMetricsOverride",{width:1280,height:900,deviceScaleFactor:1,mobile:false},library);await evaluate(library,"document.fonts.load('15px \\\"IBM Plex Sans\\\"').then(()=>true)");const libraryVisual=await evaluate(library,"(()=>{const sidebar=document.querySelector('.collection-sidebar').getBoundingClientRect(),row=document.querySelector('.collection-link').getBoundingClientRect(),icon=document.querySelector('.icon-button').getBoundingClientRect();return{sidebar:sidebar.width,row:row.height,icon:icon.width,overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,font:document.fonts.check('15px \\\"IBM Plex Sans\\\"'),family:getComputedStyle(document.documentElement).fontFamily,faces:[...document.fonts].map(face=>[face.family,face.status])}})()");assert.ok(libraryVisual.sidebar>=315&&libraryVisual.sidebar<=325&&libraryVisual.row>=42&&libraryVisual.icon>=34&&libraryVisual.overflow===0&&libraryVisual.font,JSON.stringify(libraryVisual));await send("Emulation.clearDeviceMetricsOverride",{},library);
  await send("Emulation.setDeviceMetricsOverride",{width:560,height:800,deviceScaleFactor:1,mobile:false},library);assert.equal(await evaluate(library,"getComputedStyle(document.querySelector('.library-layout')).gridTemplateColumns.split(' ').length===1 && document.documentElement.scrollWidth===document.documentElement.clientWidth"),true);await send("Emulation.clearDeviceMetricsOverride",{},library);
  assert.equal(await evaluate(library,"document.querySelector('#create-form').hidden && !document.querySelector('#show-create').hidden"),true);
  await evaluate(library,"document.querySelector('#show-create').click()");assert.equal(await evaluate(library,"!document.querySelector('#create-form').hidden && document.activeElement===document.querySelector('#collection-name')"),true);
  await evaluate(library,"document.querySelector('#collection-name').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");assert.equal(await evaluate(library,"document.querySelector('#create-form').hidden && document.activeElement===document.querySelector('#show-create')"),true);await evaluate(library,"document.querySelector('#show-create').click()");
  await evaluate(library,"document.querySelector('#collection-name').value='Reading'");await send("Input.dispatchKeyEvent",{type:"keyDown",key:"Enter",code:"Enter",windowsVirtualKeyCode:13},library);await send("Input.dispatchKeyEvent",{type:"keyUp",key:"Enter",code:"Enter",windowsVirtualKeyCode:13},library);await until(library,"document.querySelectorAll('#collection-list .collection-link').length===4 && [...document.querySelectorAll('#collection-list .collection-link')].find(button=>button.getAttribute('aria-current')==='page')?.firstElementChild.textContent==='Reading'");
  const readingId=await evaluate(library,"[...document.querySelectorAll('#collection-list .collection-link')].find(button=>button.firstElementChild.textContent==='Reading').dataset.collectionId");
  assert.equal(await evaluate(library,`(()=>{const row=document.querySelector('[data-collection-id=${JSON.stringify(readingId)}]').parentElement;const edit=row.querySelector('[data-action="rename"]');edit.focus();return getComputedStyle(row.querySelector('.collection-actions')).opacity==='1'&&document.activeElement===edit&&edit.getAttribute('aria-label')==='Rename Reading'})()`),true);
  const longCollectionName="Long-term reading list for geometric representation theory";await evaluate(library,"document.activeElement.click()");assert.equal(await evaluate(library,"document.activeElement.matches('[data-rename-id]')"),true);await evaluate(library,`document.activeElement.value=${JSON.stringify(longCollectionName)}`);await send("Input.dispatchKeyEvent",{type:"keyDown",key:"Enter",code:"Enter",windowsVirtualKeyCode:13},library);await send("Input.dispatchKeyEvent",{type:"keyUp",key:"Enter",code:"Enter",windowsVirtualKeyCode:13},library);await until(library,`[...document.querySelectorAll('#collection-list .collection-link')].some(button=>button.firstElementChild.textContent===${JSON.stringify(longCollectionName)})`);
  assert.equal(await evaluate(library,`(()=>{const button=document.querySelector('[data-collection-id=${JSON.stringify(readingId)}]'),name=button.firstElementChild;return name.textContent===${JSON.stringify(longCollectionName)}&&name.scrollWidth>=name.clientWidth&&document.documentElement.scrollWidth===document.documentElement.clientWidth})()`),true);
  await evaluate(library,`document.querySelector('[data-collection-id=${JSON.stringify(readingId)}]').parentElement.querySelector('[data-action="rename"]').click()`);await evaluate(library,"document.activeElement.value='Discarded name';document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");assert.equal(await evaluate(library,`document.querySelector('[data-collection-id=${JSON.stringify(readingId)}]').firstElementChild.textContent`),longCollectionName);
  await evaluate(library,"document.querySelector('#show-create').click();document.querySelector('#collection-name').value='Temporary';document.querySelector('#create-form').requestSubmit()");await until(library,"[...document.querySelectorAll('#collection-list .collection-link')].some(button=>button.firstElementChild.textContent==='Temporary')");
  const temporaryId=await evaluate(library,"[...document.querySelectorAll('#collection-list .collection-link')].find(button=>button.firstElementChild.textContent==='Temporary').dataset.collectionId");
  await evaluate(library,`document.querySelector('[data-collection-id=${JSON.stringify(temporaryId)}]').parentElement.querySelector('[data-action="delete"]').click()`);assert.equal(await evaluate(library,"document.querySelector('.delete-confirmation')?.textContent"),"Delete?YesCancel");await evaluate(library,"[...document.querySelectorAll('.delete-confirmation button')].find(button=>button.textContent==='Cancel').click()");assert.equal(await evaluate(library,`Boolean(document.querySelector('[data-collection-id=${JSON.stringify(temporaryId)}]'))`),true);
  await evaluate(library,`document.querySelector('[data-collection-id=${JSON.stringify(temporaryId)}]').parentElement.querySelector('[data-action="delete"]').click();document.querySelector('[data-confirm-id]').click()`);await until(library,`!document.querySelector('.delete-confirmation')&&!document.querySelector('[data-collection-id=${JSON.stringify(temporaryId)}]')&&document.querySelector('[data-collection-id=""]').getAttribute('aria-current')==='page'`);
  assert.equal(await evaluate(library,"document.querySelector('#count').textContent"),"1 paper");
  await evaluate(library,"document.querySelector('#filter').value='missing';document.querySelector('#filter').dispatchEvent(new Event('input',{bubbles:true}))");assert.equal(await evaluate(library,"document.querySelector('#count').textContent"),"0 of 1 papers");await evaluate(library,"document.querySelector('#filter').value='';document.querySelector('#filter').dispatchEvent(new Event('input',{bubbles:true}))");
  for(const name of ["Saved Papers","Important"]){await evaluate(library,`[...document.querySelectorAll('#collection-list .collection-link')].find(button=>button.firstElementChild.textContent===${JSON.stringify(name)}).click()`);assert.equal(await evaluate(library,"document.querySelectorAll('#papers .paper-row').length"),1)}
  await evaluate(arxiv,"[...document.querySelectorAll('.arxiv-collection-picker label')].find(l=>l.textContent.includes('Saved Papers')).querySelector('input').click()");await until(arxiv,"document.querySelectorAll('.arxiv-collection-picker input[type=checkbox]:checked').length===1 && document.querySelector('.arxiv-library-bookmark').getAttribute('aria-pressed')==='true'");
  await send("Page.reload",{},library);await until(library,"document.querySelectorAll('#collection-list .collection-link').length===4");
  await evaluate(library,"[...document.querySelectorAll('#collection-list .collection-link')].find(button=>button.firstElementChild.textContent==='Saved Papers').click()");assert.equal(await evaluate(library,"document.querySelectorAll('#papers .paper-row').length"),0);
  await evaluate(arxiv,"[...document.querySelectorAll('.arxiv-collection-picker label')].find(l=>l.textContent.includes('Important')).querySelector('input').click()");await until(arxiv,"document.querySelector('.arxiv-library-bookmark').getAttribute('aria-pressed')==='false'");
  await send("Page.reload",{},library);await until(library,"document.querySelectorAll('#papers .paper-row').length===0");
  await evaluate(arxiv,"document.querySelector('.arxiv-collection-picker button').click();document.querySelector('.arxiv-library-bookmark').click()");await until(arxiv,"document.querySelector('.arxiv-library-bookmark').getAttribute('aria-pressed')==='true'");

  const {sessionId:authors}=await page();await intercept(authors);await send("Page.navigate",{url:extensionUrl("authors/authors.html")},authors);await until(authors,"document.querySelectorAll('#authors .author-row').length===1");
  assert.deepEqual(await evaluate(authors,"[...document.querySelectorAll('.app-nav a')].map(link=>link.textContent)"),["Library","Following"]);
  assert.equal(await evaluate(authors,"!document.querySelector('select') && !document.querySelector('[aria-haspopup=dialog]') && !document.body.innerText.includes('Collections')"),true);
  assert.equal(await evaluate(authors,"(()=>{const name=document.querySelector('.author-row h2').getBoundingClientRect(),button=document.querySelector('.author-row button').getBoundingClientRect();return Math.abs((name.top+name.height/2)-(button.top+button.height/2))<1&&document.documentElement.scrollWidth===document.documentElement.clientWidth})()"),true);
  assert.equal(await evaluate(authors,"(()=>{const link=document.querySelector('.author-row h2 a'),original=link.textContent;link.textContent='Atsushi Takahashi with an exceptionally long research display name';const fits=document.documentElement.scrollWidth===document.documentElement.clientWidth;link.textContent=original;return fits})()"),true);
  await evaluate(authors,"document.querySelector('#authors h2 a').click()");await until(authors,"document.querySelector('#name')?.textContent==='Alex Kim' && document.querySelectorAll('.paper-row').length===1");
  assert.equal(await evaluate(authors,"document.querySelector('.local-back')?.textContent==='← Following' && document.querySelector('.local-back').getAttribute('href')==='../authors/authors.html' && !document.body.innerText.includes('Collection:') && !document.querySelector('#follow-state')"),true);
  assert.deepEqual(await evaluate(authors,"[...document.querySelectorAll('.app-nav a')].map(link=>link.textContent)"),["Library","Following"]);
  assert.equal(await evaluate(authors,"document.querySelectorAll('.year-group[aria-labelledby] > .year-list').length"),1);
  assert.equal(await evaluate(authors,"(()=>{const controls=[document.querySelector('#refresh'),document.querySelector('#open-search')];return controls.every(control=>control.querySelector('svg')&&control.getAttribute('aria-label')===control.title&&control.getBoundingClientRect().width===38&&control.getBoundingClientRect().height===38&&control.querySelector('svg').getBoundingClientRect().width===18&&control.tabIndex===0)&&controls[0].tagName==='BUTTON'&&controls[1].tagName==='A'&&controls[1].href.includes('https://arxiv.org/search/')&&!controls[1].hasAttribute('target')&&[...document.querySelectorAll('[data-arxiv-link]')].every(link=>!link.hasAttribute('target'))&&document.documentElement.scrollWidth===document.documentElement.clientWidth})()"),true);
  await evaluate(authors,"(()=>{window.__refreshActivations=0;const button=document.querySelector('#refresh');button.addEventListener('click',()=>window.__refreshActivations++);button.click()})()");await until(authors,"window.__refreshActivations===1&&!document.querySelector('#refresh').disabled&&!document.querySelector('#status').textContent");
  const authorPageUrl=await evaluate(authors,"location.href");await nativeClick(authors,".paper-row h2 a");await until(authors,"location.href.startsWith('https://arxiv.org/abs/2609.01234')");await send("Page.navigate",{url:authorPageUrl},authors);await until(authors,"document.querySelector('#name')?.textContent==='Alex Kim'&&document.querySelectorAll('.paper-row').length===1");
  const modifierTarget=await createdTarget(()=>nativeClick(authors,".paper-row h2 a",2),target=>target.url.startsWith("https://arxiv.org/abs/2609.01234"));assert.equal(await evaluate(authors,"location.href"),authorPageUrl);await send("Target.closeTarget",{targetId:modifierTarget.targetId});
  await evaluate(popup,"document.querySelector('#show-preferences').click()");assert.equal(await evaluate(popup,"!document.querySelector('#preferences').hidden&&document.activeElement===document.querySelector('#open-arxiv-new-tab')"),true);await evaluate(popup,"document.querySelector('#open-arxiv-new-tab').click()");await until(popup,"document.querySelector('#open-arxiv-new-tab').checked&&!document.querySelector('#open-arxiv-new-tab').disabled");await send("Page.reload",{},popup);await until(popup,"document.querySelector('#open-arxiv-new-tab')?.checked===true");
  await send("Page.reload",{},authors);await until(authors,"document.querySelector('#name')?.textContent==='Alex Kim'&&document.querySelectorAll('.paper-row').length===1&&document.querySelector('#open-search').target==='_blank'");
  assert.equal(await evaluate(authors,"[...document.querySelectorAll('[data-arxiv-link]')].every(link=>link.target==='_blank')"),true);
  const preferenceTarget=await createdTarget(()=>nativeClick(authors,"#open-search"),target=>target.url.startsWith("https://arxiv.org/search/"));assert.equal(await evaluate(authors,"location.href"),authorPageUrl);await send("Target.closeTarget",{targetId:preferenceTarget.targetId});
  assert.match(await evaluate(authors,"document.querySelector('.paper-row h2').textContent"),/Recent mirror symmetry/);await evaluate(authors,"document.querySelector('.paper-row .bookmark').click()");await until(authors,"document.querySelector('.paper-row .bookmark').getAttribute('aria-pressed')==='true'");
  await evaluate(authors,"document.querySelector('.local-back').click()");await until(authors,"document.querySelectorAll('#authors .author-row').length===1");
  await send("Page.reload",{},library);await until(library,"document.querySelectorAll('#papers .paper-row').length===2");

  const {sessionId:search}=await page();await intercept(search);await send("Page.navigate",{url:extensionUrl("search/search.html")},search);await until(search,"document.querySelectorAll('#field option').length===8");
  await evaluate(search,"document.querySelector('#query').value='mirror symmetry for K3';document.querySelector('#field').value='mirror-symmetry';document.querySelector('#search-form').requestSubmit()");await until(search,"document.querySelectorAll('#results .paper-row').length===1");
  const lengths=[];for(const mode of ["exact","balanced","broad"]){lengths.push(await evaluate(search,`document.querySelector('input[value=${JSON.stringify(mode)}]').click();document.querySelector('#search-form').dispatchEvent(new Event('input'));document.querySelector('#preview').textContent.length`))}assert.ok(lengths[0]<lengths[1]&&lengths[1]<lengths[2]);

  await send("Page.reload",{},arxiv);await until(arxiv,"document.querySelector('.arxiv-library-bookmark')?.getAttribute('aria-pressed')==='true' && document.querySelector('.authors .arxiv-library-button')?.getAttribute('aria-pressed')==='true'");
  const stored=await evaluate(library,"(async()=>{const {ChromeLocalStorage}=await import('../lib/storage.js');return new ChromeLocalStorage().read()})()");assert.equal(stored.schemaVersion,5);assert.equal(stored.authorPaperCaches.length,1);assert.equal(stored.favorites.length,2);assert.equal(stored.paperCollections.length,3);assert.equal(stored.paperMemberships.length,2);assert.equal(stored.memberships.length,1);assert.equal(stored.settings.openArxivLinksInNewTab,true);assert.notEqual(stored.settings.lastUsedPaperCollectionId,stored.settings.lastUsedAuthorCollectionId);
  assert.deepEqual(runtimeErrors,[]);assert.deepEqual(asyncErrors,[]);console.log("BROWSER SMOKE PASS: stable popup, wide Library sidebar, IBM Plex, native arXiv navigation preference, author controls, and persisted shared state");
}finally{await send("Browser.close").catch(()=>{});chrome.kill();await new Promise(resolve=>setTimeout(resolve,300));await rm(profile,{recursive:true,force:true})}
