import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root=fileURLToPath(new URL("../",import.meta.url));const profile=await mkdtemp(join(tmpdir(),"arxiv-smoke-"));
const chrome=spawn(process.env.CHROME_BIN||"/usr/bin/google-chrome",["--headless=new","--no-sandbox","--disable-gpu","--disable-dev-shm-usage","--no-first-run","--disable-background-networking","--remote-debugging-pipe","--enable-unsafe-extension-debugging",`--user-data-dir=${profile}`,"about:blank"],{stdio:["ignore","ignore","pipe","pipe","pipe"]});
let nextId=0,buffer="",errors="";const pending=new Map(),listeners=[],runtimeErrors=[],asyncErrors=[];chrome.stderr.on("data",d=>errors+=d);
for(const stream of [chrome.stdio[3],chrome.stdio[4]])stream.on("error",e=>asyncErrors.push(e.message));
chrome.stdio[4].on("data",data=>{buffer+=data;let index;while((index=buffer.indexOf("\0"))>=0){const message=JSON.parse(buffer.slice(0,index));buffer=buffer.slice(index+1);if(message.id){const callback=pending.get(message.id);pending.delete(message.id);message.error?callback?.reject(new Error(JSON.stringify(message.error))):callback?.resolve(message.result)}else listeners.forEach(listener=>listener(message))}});
function send(method,params={},sessionId){return new Promise((resolve,reject)=>{const id=++nextId;const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`Timeout: ${method}\n${errors.slice(-2000)}`))},15000);pending.set(id,{resolve:value=>{clearTimeout(timer);resolve(value)},reject:error=>{clearTimeout(timer);reject(error)}});chrome.stdio[3].write(JSON.stringify({id,method,params,sessionId})+"\0")})}
async function evaluate(sessionId,expression){const result=await send("Runtime.evaluate",{expression,returnByValue:true,awaitPromise:true},sessionId);if(result.exceptionDetails)throw new Error(JSON.stringify(result.exceptionDetails));return result.result.value}
async function until(sessionId,expression){for(let i=0;i<80;i++){if(await evaluate(sessionId,expression))return;await new Promise(resolve=>setTimeout(resolve,100))}throw new Error(`Condition not met: ${expression}\n${await evaluate(sessionId,"document.body.innerText")}`)}
async function page(){const {targetId}=await send("Target.createTarget",{url:"about:blank"});const {sessionId}=await send("Target.attachToTarget",{targetId,flatten:true});await send("Page.enable",{},sessionId);await send("Runtime.enable",{},sessionId);return{targetId,sessionId}}
const fixture=(await readFile(join(root,"tests/fixtures/arxiv-abstract.html"),"utf8")).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"");
const atom=`<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom"><entry><id>https://arxiv.org/abs/2609.01234v1</id><title>Recent mirror symmetry paper</title><summary>A normalized result for browser verification.</summary><published>2026-09-20T00:00:00Z</published><author><name>Alex Kim</name></author><category term="math.AG"/></entry></feed>`;
const intercepted=new Map();listeners.push(message=>{if(message.method==="Runtime.exceptionThrown")runtimeErrors.push(message.params);if(message.method==="Runtime.consoleAPICalled"&&message.params.type==="error")runtimeErrors.push(message.params.args);if(message.method==="Fetch.requestPaused"&&intercepted.has(message.sessionId)){const url=message.params.request.url;const body=url.startsWith("https://export.arxiv.org/")?atom:fixture;void send("Fetch.fulfillRequest",{requestId:message.params.requestId,responseCode:200,responseHeaders:[{name:"Content-Type",value:url.includes("export.arxiv.org")?"application/atom+xml":"text/html; charset=utf-8"}],body:Buffer.from(message.params.resourceType==="Document"||url.includes("export.arxiv.org")?body:"").toString("base64")},message.sessionId).catch(e=>asyncErrors.push(e.message))}});
async function intercept(sessionId){intercepted.set(sessionId,true);await send("Fetch.enable",{patterns:[{urlPattern:"https://*"}]},sessionId)}

try{
  const loaded=await send("Extensions.loadUnpacked",{path:join(root,"extension")});const extensionId=loaded.id;const extensionUrl=path=>`chrome-extension://${extensionId}/src/${path}`;
  const {sessionId:arxiv}=await page();await intercept(arxiv);await send("Page.navigate",{url:"https://arxiv.org/abs/2401.00001"},arxiv);
  await until(arxiv,"document.querySelector('.arxiv-library-bookmark') && document.querySelectorAll('.authors .arxiv-library-button').length===2 && !document.querySelector('.arxiv-library-bookmark').disabled");
  assert.equal(await evaluate(arxiv,"document.querySelector('.arxiv-library-bookmark').getBoundingClientRect().width>=36 && document.querySelector('.arxiv-library-bookmark svg').getBoundingClientRect().width>=20"),true);
  assert.equal(await evaluate(arxiv,"(()=>{const button=document.querySelector('.authors .arxiv-library-button');const rect=button.getBoundingClientRect();return button.textContent==='Follow'&&button.getAttribute('aria-pressed')==='false'&&!button.hasAttribute('aria-haspopup')&&rect.height>=36&&rect.width>=78})()"),true);
  await evaluate(arxiv,"document.querySelector('.arxiv-library-bookmark').click()");await until(arxiv,"document.querySelector('.arxiv-library-bookmark').getAttribute('aria-pressed')==='true' && !document.querySelector('.arxiv-library-bookmark').disabled");
  await evaluate(arxiv,"document.querySelector('.authors .arxiv-library-button').click()");await until(arxiv,"document.querySelector('.authors .arxiv-library-button').getAttribute('aria-pressed')==='true'");
  assert.equal(await evaluate(arxiv,"document.querySelector('.authors .arxiv-library-button').textContent"),"Following");
  await evaluate(arxiv,"document.querySelector('.authors .arxiv-library-button').click()");await until(arxiv,"document.querySelector('.authors .arxiv-library-button').getAttribute('aria-pressed')==='false'");
  await evaluate(arxiv,"document.querySelector('.authors .arxiv-library-button').click()");await until(arxiv,"document.querySelector('.authors .arxiv-library-button').getAttribute('aria-pressed')==='true'");
  assert.equal(await evaluate(arxiv,"document.querySelector('.arxiv-library-bookmark').title"),"Manage collections");
  await evaluate(arxiv,"document.querySelector('.arxiv-library-bookmark').click()");await until(arxiv,"document.querySelector('.arxiv-collection-picker') && document.querySelectorAll('.arxiv-collection-picker input[type=checkbox]:checked').length===1");
  assert.equal(await evaluate(arxiv,"[...document.querySelectorAll('.arxiv-collection-picker label')].find(l=>l.textContent.includes('Saved Papers'))?.querySelector('input').checked"),true);
  await evaluate(arxiv,"document.querySelector('.arxiv-collection-picker input[type=text]').value='Important';document.querySelector('.arxiv-collection-picker form').requestSubmit()");
  await until(arxiv,"document.querySelectorAll('.arxiv-collection-picker input[type=checkbox]:checked').length===2");

  const {targetId:popupPageTarget,sessionId:popup}=await page();await send("Page.navigate",{url:extensionUrl("popup/popup.html")},popup);await until(popup,"document.querySelector('#saved-count')?.textContent==='1' && document.querySelector('#following-count')?.textContent==='1'");
  assert.deepEqual(await evaluate(popup,"chrome.action.openPopup().then(()=>({ok:true}),error=>({ok:false,error:error.message}))"),{ok:true});
  let actionPopup;for(let i=0;i<30&&!actionPopup;i++){const targets=await send("Target.getTargets");actionPopup=targets.targetInfos.find(target=>target.type==="page"&&target.url===extensionUrl("popup/popup.html")&&target.targetId!==popupPageTarget);if(!actionPopup)await new Promise(resolve=>setTimeout(resolve,50))}assert.ok(actionPopup,"Chrome action popup did not open");
  const {sessionId:actionPopupSession}=await send("Target.attachToTarget",{targetId:actionPopup.targetId,flatten:true});await send("Runtime.enable",{},actionPopupSession);await until(actionPopupSession,"document.readyState==='complete' && document.querySelector('#saved-count')?.textContent==='1' && document.querySelector('#following-count')?.textContent==='1'");
  const geometryExpression="(()=>{const html=document.documentElement,body=document.body,buttons=[...document.querySelectorAll('nav button')].map(button=>{const rect=button.getBoundingClientRect();return [rect.width,rect.height]});return{viewport:[innerWidth,innerHeight],body:[body.getBoundingClientRect().width,body.getBoundingClientRect().height],overflow:[html.clientWidth,html.scrollWidth,body.clientWidth,body.scrollWidth],buttons}})()";
  const popupGeometry=await evaluate(actionPopupSession,geometryExpression);assert.equal(popupGeometry.viewport[0],408);assert.equal(popupGeometry.overflow[0],popupGeometry.overflow[1]);assert.equal(popupGeometry.overflow[2],popupGeometry.overflow[3]);assert.deepEqual(popupGeometry.buttons[0],popupGeometry.buttons[1]);
  for(let i=0;i<10;i++){await new Promise(resolve=>setTimeout(resolve,50));assert.deepEqual(await evaluate(actionPopupSession,geometryExpression),popupGeometry)}
  await evaluate(actionPopupSession,"document.querySelector('nav button').focus()");assert.deepEqual(await evaluate(actionPopupSession,geometryExpression),popupGeometry);
  const buttonCenter=await evaluate(actionPopupSession,"(()=>{const rect=document.querySelector('nav button').getBoundingClientRect();return{x:rect.left+rect.width/2,y:rect.top+rect.height/2}})()");await send("Input.dispatchMouseEvent",{type:"mouseMoved",x:buttonCenter.x,y:buttonCenter.y},actionPopupSession);assert.deepEqual(await evaluate(actionPopupSession,geometryExpression),popupGeometry);
  assert.deepEqual(await evaluate(popup,"[...document.querySelectorAll('nav button')].map(button=>button.textContent)"),["Library","Following"]);
  assert.equal(await evaluate(popup,"(()=>{const body=document.body.getBoundingClientRect(),main=getComputedStyle(document.querySelector('main')),buttons=[...document.querySelectorAll('nav button')].map(button=>button.getBoundingClientRect()),nav=document.querySelector('nav').getBoundingClientRect();return body.width===408&&main.paddingLeft===main.paddingRight&&buttons[0].width===buttons[1].width&&buttons[0].height===buttons[1].height&&buttons[0].height>=38&&Math.abs((buttons[1].left-buttons[0].right)-10)<.1&&Math.abs(nav.left-body.left-20)<.1&&Math.abs(body.right-nav.right-20)<.1})()"),true);
  await evaluate(popup,"window.close=()=>{}");
  for(const [label,path] of [["Library","library/library.html"],["Following","authors/authors.html"]]){await evaluate(popup,`[...document.querySelectorAll('button')].find(b=>b.textContent===${JSON.stringify(label)}).click()`);for(let i=0;i<30;i++){const targets=await send("Target.getTargets");if(targets.targetInfos.some(t=>t.url===extensionUrl(path)))break;if(i===29)assert.fail(`${label} did not open ${path}`);await new Promise(r=>setTimeout(r,100))}}

  const {sessionId:library}=await page();await send("Page.navigate",{url:extensionUrl("library/library.html")},library);await until(library,"document.querySelectorAll('#papers .paper-row').length===1");assert.equal(await evaluate(library,"document.querySelector('#papers h2').textContent"),"A sample paper");
  assert.equal(await evaluate(library,"[...document.querySelectorAll('.app-nav a')].some(link=>link.textContent==='Search')"),false);
  assert.deepEqual(await evaluate(library,"[...document.querySelectorAll('.app-nav a')].map(link=>link.textContent)"),["Library","Following"]);
  assert.deepEqual(await evaluate(library,"[...document.querySelectorAll('#collection-list .collection-link')].map(button=>[button.firstElementChild.textContent,button.lastElementChild.textContent,button.getAttribute('aria-current')])"),[["All Saved","1","page"],["Saved Papers","1",null],["Important","1",null]]);
  assert.equal(await evaluate(library,"Boolean(document.querySelector('aside nav')) && !document.querySelector('select')"),true);
  await send("Emulation.setDeviceMetricsOverride",{width:560,height:800,deviceScaleFactor:1,mobile:false},library);assert.equal(await evaluate(library,"getComputedStyle(document.querySelector('.library-layout')).gridTemplateColumns.split(' ').length===1 && document.documentElement.scrollWidth===document.documentElement.clientWidth"),true);await send("Emulation.clearDeviceMetricsOverride",{},library);
  assert.equal(await evaluate(library,"document.querySelector('#create-form').hidden && !document.querySelector('#show-create').hidden"),true);
  await evaluate(library,"document.querySelector('#show-create').click()");assert.equal(await evaluate(library,"!document.querySelector('#create-form').hidden && document.activeElement===document.querySelector('#collection-name')"),true);
  await evaluate(library,"document.querySelector('#collection-name').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");assert.equal(await evaluate(library,"document.querySelector('#create-form').hidden && document.activeElement===document.querySelector('#show-create')"),true);await evaluate(library,"document.querySelector('#show-create').click()");
  await evaluate(library,"document.querySelector('#collection-name').value='Reading';document.querySelector('#create-form').requestSubmit()");await until(library,"document.querySelectorAll('#collection-list .collection-link').length===4 && [...document.querySelectorAll('#collection-list .collection-link')].find(button=>button.getAttribute('aria-current')==='page')?.firstElementChild.textContent==='Reading'");
  assert.equal(await evaluate(library,"document.querySelector('#create-form').hidden && document.querySelector('#manage-form').hidden && !document.querySelector('#show-manage').hidden"),true);
  await evaluate(library,"document.querySelector('#show-manage').click()");assert.equal(await evaluate(library,"!document.querySelector('#manage-form').hidden"),true);await evaluate(library,"document.querySelector('#close-manage').click()");
  for(const name of ["Saved Papers","Important"]){await evaluate(library,`[...document.querySelectorAll('#collection-list .collection-link')].find(button=>button.firstElementChild.textContent===${JSON.stringify(name)}).click()`);assert.equal(await evaluate(library,"document.querySelectorAll('#papers .paper-row').length"),1)}
  await evaluate(arxiv,"[...document.querySelectorAll('.arxiv-collection-picker label')].find(l=>l.textContent.includes('Saved Papers')).querySelector('input').click()");await until(arxiv,"document.querySelectorAll('.arxiv-collection-picker input[type=checkbox]:checked').length===1 && document.querySelector('.arxiv-library-bookmark').getAttribute('aria-pressed')==='true'");
  await send("Page.reload",{},library);await until(library,"document.querySelectorAll('#collection-list .collection-link').length===4");
  await evaluate(library,"[...document.querySelectorAll('#collection-list .collection-link')].find(button=>button.firstElementChild.textContent==='Saved Papers').click()");assert.equal(await evaluate(library,"document.querySelectorAll('#papers .paper-row').length"),0);
  await evaluate(arxiv,"[...document.querySelectorAll('.arxiv-collection-picker label')].find(l=>l.textContent.includes('Important')).querySelector('input').click()");await until(arxiv,"document.querySelector('.arxiv-library-bookmark').getAttribute('aria-pressed')==='false'");
  await send("Page.reload",{},library);await until(library,"document.querySelectorAll('#papers .paper-row').length===0");
  await evaluate(arxiv,"document.querySelector('.arxiv-collection-picker button').click();document.querySelector('.arxiv-library-bookmark').click()");await until(arxiv,"document.querySelector('.arxiv-library-bookmark').getAttribute('aria-pressed')==='true'");

  const {sessionId:authors}=await page();await intercept(authors);await send("Page.navigate",{url:extensionUrl("authors/authors.html")},authors);await until(authors,"document.querySelectorAll('#authors .author-row').length===1");
  assert.deepEqual(await evaluate(authors,"[...document.querySelectorAll('.app-nav a')].map(link=>link.textContent)"),["Library","Following"]);
  assert.equal(await evaluate(authors,"!document.querySelector('select') && !document.querySelector('[aria-haspopup=dialog]') && !document.body.innerText.includes('Collections')"),true);
  assert.equal(await evaluate(authors,"(()=>{const name=document.querySelector('.author-row h2').getBoundingClientRect(),button=document.querySelector('.author-row button').getBoundingClientRect();return Math.abs((name.top+name.height/2)-(button.top+button.height/2))<1})()"),true);
  await evaluate(authors,"document.querySelector('#authors h2 a').click()");await until(authors,"document.querySelector('#name')?.textContent==='Alex Kim' && document.querySelectorAll('.paper-row').length===1");
  assert.equal(await evaluate(authors,"document.querySelector('.local-back')?.textContent==='← Following' && document.querySelector('.local-back').getAttribute('href')==='../authors/authors.html' && !document.body.innerText.includes('Collection:') && !document.querySelector('#follow-state')"),true);
  assert.deepEqual(await evaluate(authors,"[...document.querySelectorAll('.app-nav a')].map(link=>link.textContent)"),["Library","Following"]);
  assert.equal(await evaluate(authors,"document.querySelectorAll('.year-group[aria-labelledby] > .year-list').length"),1);
  assert.match(await evaluate(authors,"document.querySelector('.paper-row h2').textContent"),/Recent mirror symmetry/);await evaluate(authors,"document.querySelector('.paper-row .bookmark').click()");await until(authors,"document.querySelector('.paper-row .bookmark').getAttribute('aria-pressed')==='true'");
  await evaluate(authors,"document.querySelector('.local-back').click()");await until(authors,"document.querySelectorAll('#authors .author-row').length===1");
  await send("Page.reload",{},library);await until(library,"document.querySelectorAll('#papers .paper-row').length===2");

  const {sessionId:search}=await page();await intercept(search);await send("Page.navigate",{url:extensionUrl("search/search.html")},search);await until(search,"document.querySelectorAll('#field option').length===8");
  await evaluate(search,"document.querySelector('#query').value='mirror symmetry for K3';document.querySelector('#field').value='mirror-symmetry';document.querySelector('#search-form').requestSubmit()");await until(search,"document.querySelectorAll('#results .paper-row').length===1");
  const lengths=[];for(const mode of ["exact","balanced","broad"]){lengths.push(await evaluate(search,`document.querySelector('input[value=${JSON.stringify(mode)}]').click();document.querySelector('#search-form').dispatchEvent(new Event('input'));document.querySelector('#preview').textContent.length`))}assert.ok(lengths[0]<lengths[1]&&lengths[1]<lengths[2]);

  await send("Page.reload",{},arxiv);await until(arxiv,"document.querySelector('.arxiv-library-bookmark')?.getAttribute('aria-pressed')==='true' && document.querySelector('.authors .arxiv-library-button')?.getAttribute('aria-pressed')==='true'");
  const stored=await evaluate(library,"(async()=>{const {ChromeLocalStorage}=await import('../lib/storage.js');return new ChromeLocalStorage().read()})()");assert.equal(stored.schemaVersion,5);assert.equal(stored.authorPaperCaches.length,1);assert.equal(stored.favorites.length,2);assert.equal(stored.paperCollections.length,3);assert.equal(stored.paperMemberships.length,2);assert.equal(stored.memberships.length,1);assert.notEqual(stored.settings.lastUsedPaperCollectionId,stored.settings.lastUsedAuthorCollectionId);
  assert.deepEqual(runtimeErrors,[]);assert.deepEqual(asyncErrors,[]);console.log("BROWSER SMOKE PASS: stable popup, Library sidebar, author navigation, paper collections, and persisted shared state");
}finally{await send("Browser.close").catch(()=>{});chrome.kill();await new Promise(resolve=>setTimeout(resolve,300));await rm(profile,{recursive:true,force:true})}
